name: CI-main-nuget

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
        
    - name: Setup Nuget
      uses: NuGet/setup-nuget@v2.0.1
      
    - name: Prepare Artifacts
      run: |
        mkdir artifacts
        mkdir artifacts/lib
        mkdir artifacts/images
        
    - name: Build with dotnet
      run: |
        version=$(grep -oP -m 1 '\* \K[0-9]*\.[0-9]*\.[0-9]*' ReleaseNotes.md)
        echo Version=$version
        dotnet build --configuration Release ./IctBaden.Config.sln -p:AssemblyVersion=$version -p:PackageVersion=$version -p:Version=1.0
        cp IctBaden.Config/bin/Release/net8.0/IctBaden.Config.dll artifacts/lib
        
    - name: Test with dotnet
      run: |
        version=$(grep -oP -m 1 '\* \K[0-9]*\.[0-9]*\.[0-9]*' ReleaseNotes.md)
        echo Version=$version
        dotnet test ./IctBaden.Config.sln --configuration Release -p:AssemblyVersion=$version -p:PackageVersion=$version -p:Version=1.0
        
    - name: Pack Nuget
      run: |
        version=$(grep -oP -m 1 '\* \K[0-9]*\.[0-9]*\.[0-9]*' ReleaseNotes.md)
        echo Version=$version
        cd artifacts
        nuget pack ../IctBaden.Config.nuspec -BasePath . -Version $version
        
    - name: Publish NuGet
      run: |
        version=$(grep -oP -m 1 '\* \K[0-9]*\.[0-9]*\.[0-9]*' ReleaseNotes.md)
        echo Version=$version
        dotnet nuget push artifacts/*.nupkg --source https://www.nuget.org --api-key ${{ secrets.NugetKey }}
